title: bruci.pw
author: bruci
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm gonna chuck things here sometimes

# social links
twitter_username: your-twitter-handle
github_username:  Bruciii

show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: mattvh/solar-theme-jekyll

